name: designpadawan
favicon: null
layout_spectrum: 0.5267786118201911
typography_spectrum: 0.6091535608284175
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.04943288187496364
  lightness: 0.26821081596426666
  saturation: 0.7269480659160763
  rhythmicContrast: 0.87355821672827
purpose: []
